### ISSUE TITLE
Handling back buton behavior on Android

### ISSUE THREAD

**Issue by jjzazuet** [niftylettuce/react-native-loading-spinner-overlay#29]
Hi. Very cool component!

I have a question. Currently, when my application is showing the spinner component (for now just setting it always to `visible` as a learning example) and the user hits the back button, the spinner will disappear and allow me to interact with the underlying elements in the UI.

Now, if I change something in the UI that causes a re-render, then the spinner controll willl re-appear (since I'm always setting `visible` to `true`), but the same thing will happen if I hit the Android hardware back button.

Is this an event that could be blocked by the Spinner component itself? Or is this something I'd need to handle in my application?

Thanks!

**Comment by niftylettuce** [comment]
Thanks for your feedback.  I'm not sure what's going on here - I haven't the time to test and I don't even know if my XCode simulator is still installed.  I'll gladly accept a PR and another maintainer here!  My time with RN is super limited for the next bit of time 😦

**Comment by b8ne** [comment]
hey @jjzazuet how did you go with this? I just had a quick look, react native does provide a onBack listener, however it will depend on your implementation.  ie. if you have multiple listeners or nested scenes/navigation the experience may vary.  It would also need to bind to your containers state, and not this package. Because of this I wouldnt recommend implementing a method specific to this package, but rather to your project.
I found https://github.com/fractaltech/react-native-onback to be pretty simply but powerful.

**Comment by jjzazuet** [comment]
Hey @b8ne, so what I ended up doing was wrapping `Spinner` under my app specific component (which is connected to the Redux state), and then just intercepting the Android back event with the `BackAndroid` api offered by Facebook. So yeah I think it makes sense to close this issue report. Thanks for your help!

**Comment by urska19** [comment]
Hi.

I know this issue is closed for a while now, but maybe following comment will still help someone. When back button on Android is pressed, Spinner disappears, because of the Modal's prop onRequestClose, which is set to [close the Modal](https://github.com/niftylettuce/react-native-loading-spinner-overlay/blob/master/src/index.js#L130). Using `onRequestClose={() => {}}` instead, will prevent from closing the Modal and Spinner will be visible until the visibility is changed.

Best.
